# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squadbase < Formula
  desc "Squadbase CLI"
  homepage "https://github.com/squadbase/squadbase"
  version "0.1.0-beta.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.1/squadbase_0.1.0-Beta.1_darwin_x86_64.tar.gz"
      sha256 "765a19261d668a5f15476e3670efff761030e515b1b1c0cc55023f15e045455d"

      def install
        bin.install "squadbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.1/squadbase_0.1.0-Beta.1_darwin_arm64.tar.gz"
      sha256 "6770609822bd6b862f5fd59f654024c96c4a295dd76a9ba68ca4717350d2a4dc"

      def install
        bin.install "squadbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.1/squadbase_0.1.0-Beta.1_linux_x86_64.tar.gz"
        sha256 "01438971f348d203617aad4c0c209b9fedcc5feaaaa7de770207f4c01f849993"

        def install
          bin.install "squadbase"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.1/squadbase_0.1.0-Beta.1_linux_arm64.tar.gz"
        sha256 "e34529c449f16dd7920059a09b50bbba725aa2b5b032009f88e4a2fb9da84d9a"

        def install
          bin.install "squadbase"
        end
      end
    end
  end

  test do
    system "#{bin}/squadbase --version"
  end
end
