# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Squadbase CLI"
  homepage "https://github.com/squadbase/squadbase"
  version "0.1.0-beta.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.2/squad_0.1.0-Beta.2_darwin_x86_64.tar.gz"
      sha256 "5044a92ae2b146bab95bd1b0e58de19c7f5b5cd8967ef961db0d9afe697f8b53"

      def install
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.2/squad_0.1.0-Beta.2_darwin_arm64.tar.gz"
      sha256 "22685502ef5e23160d210e4f4c20215f6bf1afff2ade6c82b335475e3b4401a0"

      def install
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.2/squad_0.1.0-Beta.2_linux_x86_64.tar.gz"
        sha256 "0a6320e2832c0306d517b4b129e109a3f4a6399bfb5b5eea4ab3d048eb598767"

        def install
          bin.install "squad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.2/squad_0.1.0-Beta.2_linux_arm64.tar.gz"
        sha256 "e5a35eed53185915e0b2e6f4ca8179c6aa6ea37edf2df2d536aad20e338ca71f"

        def install
          bin.install "squad"
        end
      end
    end
  end

  test do
    system "#{bin}/squad --version"
  end
end
