# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Squadbase CLI"
  homepage "https://github.com/squadbase/squadbase"
  version "0.1.0-beta.6"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.6/squad_0.1.0-beta.6_darwin_x86_64.tar.gz"
      sha256 "23a1b614920205e36d125303e9ce8f68414006947beefed16aa7ef14650f7f6c"

      def install
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.6/squad_0.1.0-beta.6_darwin_arm64.tar.gz"
      sha256 "e29c6e6e83e90fcb24888a2bd38012507ab3ac22d31d6541b58cf292ff10ba50"

      def install
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.6/squad_0.1.0-beta.6_linux_x86_64.tar.gz"
        sha256 "c1316f13027b3dbc3847a686298194885f292c7013f91823ed57b2a44633e882"

        def install
          bin.install "squad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.6/squad_0.1.0-beta.6_linux_arm64.tar.gz"
        sha256 "edef34709afee708fff5a4860a7d8ca33687b8c45cec29d0db1b8bdbc4ebc07a"

        def install
          bin.install "squad"
        end
      end
    end
  end

  test do
    system "#{bin}/squad --version"
  end
end
