# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Squadbase CLI"
  homepage "https://github.com/squadbase/squadbase"
  version "0.1.0-beta.12"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.12/squad_0.1.0-Beta.12_darwin_x86_64.tar.gz"
      sha256 "8ed7166787a66e04162c570704c51eac0860fbedbc284e750d733dd45cf70d1e"

      def install
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.12/squad_0.1.0-Beta.12_darwin_arm64.tar.gz"
      sha256 "41124c28ba8b1e65494bd3df5123eeb01f4766882efcef0536331c05587a52f5"

      def install
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.12/squad_0.1.0-Beta.12_linux_x86_64.tar.gz"
        sha256 "53f203e64b73a11d0a172d810283aeed4c9fb880e1e5e2bb6d2181efcd0598de"

        def install
          bin.install "squad"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/squadbase/squadbase/releases/download/v0.1.0-beta.12/squad_0.1.0-Beta.12_linux_arm64.tar.gz"
        sha256 "941246b487145e90ecafab7f28b913bb10d77ef9b63cb0b5d481e593d2aac04f"

        def install
          bin.install "squad"
        end
      end
    end
  end

  test do
    system "#{bin}/squad --version"
  end
end
